name: Discord Webhook

on: [push]

jobs:
  report-status:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Set up Java JDK 11
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Run Discord Webhook
      uses: baked-libs/discord-webhook@main
      with:
        id: ${{ secrets.1051433756424147034 }}
        token: ${{ secrets.uFwKEocwcv0nW6fqvBa0W3hVQgOJVC5-kLZvTLEDqeiuhoHPH0e-_H3ne9V4A4HDMCch }}